# Generated by Django 5.2.3 on 2025-07-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musclegroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
